# Generated by Django 5.1.3 on 2024-11-18 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(choices=[('tb2', 'TB2'), ('tb3', 'TB3'), ('akinci', 'AKINCI'), ('kizilelma', 'KIZILELMA')], max_length=50)),
                ('production_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('kanat_takim', 'Kanat Takımı'), ('govde_takim', 'Gövde Takımı'), ('kuyruk_takim', 'Kuyruk Takımı'), ('aviyonik_takim', 'Aviyonik Takımı'), ('montaj_takim', 'Montaj Takımı')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('kanat', 'Kanat'), ('govde', 'Gövde'), ('kuyruk', 'Kuyruk'), ('aviyonik', 'Aviyonik')], max_length=50)),
                ('part_aircraft', models.CharField(choices=[('tb2', 'TB2'), ('tb3', 'TB3'), ('akinci', 'AKINCI'), ('kizilelma', 'KIZILELMA')], max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('assigned_aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aircraft')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.team')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='produced_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrafts', to='api.team'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
